### ISSUE TITLE
Your SQLite3 library does not support FTS4

### ISSUE THREAD

**Issue by py4h0n** [vulnersCom/getsploit#3]
python script on mac , full text search sqlite database, tips:Your SQLite3 library does not support FTS4.， recompile sqlite， command "pragma compile_options" shows ENABLED_ FTS4，but python script still shows not support FTS4. Any solution？
system & program version
macos Sierra develop beta3
python 2.7.13
sqlite3 3.19.3

**Comment by vulnersCom** [comment]
Fixed in the last commit.
Please, check.

**Comment by py4h0n** [comment]
Still have the problem.
python 2.7.* in-bulit sqlite3 module, not have enabled FTS4 feature
in 
my test:

Python 2.7.10 (default, Feb  7 2017, 00:08:15)
Type "copyright", "credits" or "license" for more information.

IPython 4.2.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import sqlite3

In [2]: con = sqlite3.connect('getsploit.db')

In [3]: cur = con.cursor()

In [4]: for (v, ) in cur.execute('pragma compile_options'):
   ...:     print v
   ...:
COMPILER=clang-8.0.0
ENABLE_API_ARMOR
ENABLE_FTS3
ENABLE_FTS3_PARENTHESIS
ENABLE_JSON1
ENABLE_LOCKING_STYLE=1
ENABLE_RTREE
ENABLE_UPDATE_DELETE_LIMIT
HAS_CODEC
HAVE_ISNAN
MAX_MMAP_SIZE=1073741824
OMIT_AUTORESET
OMIT_BUILTIN_TEST
OMIT_LOAD_EXTENSION
SYSTEM_MALLOC
THREADSAFE=2

maybe for python 2.7.*, you should change you code like this:
for (val,) in cursor.execute('pragma compile_options'):
        if 'FTS4' in val:
==>
for (val,) in cursor.execute('pragma compile_options'):
        if 'FTS3' in val:

It works for me~

**Comment by vulnersCom** [comment]
Wow.
It looks like back-compatibility from FTS4 to FTS3?
So with
if 'FTS3' in val
fix everything worked correctly with -l option? 
./getsploit.py -l wordpress

**Comment by py4h0n** [comment]
http://www.sqlite.org/fts3.html
FTS3 and FTS4 are nearly identical. They share most of their code in common, and their interfaces are the same.

**Comment by vulnersCom** [comment]
Got it.
Fixed.
